- hosts: all
  gather_facts: yes
  become: yes
  tasks:

  - name: Gather os specific variables
    include_vars: "{{ item }}" 
    with_first_found:
    - "vars/{{ ansible_distribution_release | lower }}.yml"
    - "vars/{{ ansible_distribution_version | lower }}.yml"
    tags: 
      - set-vars

  - name: Update all packages to the latest version
    apt:
      state: latest
      update_cache: yes
    tags:
      - install-update

  - name: Install base packages
    ansible.builtin.apt:
      pkg: 
        "{{ packages }}"
      state: latest
      update_cache: yes
    tags:
      - install-base-packages

  ## docker
  #########################################
  - name: Docker - Installation
    ansible.builtin.apt:
      pkg:
        - docker.io
      state: latest
      update_cache: yes
    tags:
      - install-docker

  - name: Docker - Enable docker on systemd
    ansible.builtin.systemd:
      name: docker
      enabled: yes
      state: started
    tags:
      - install-docker

  - name: Docker - Add vagrant to docker group
    user:
      name: vagrant
      groups: docker
      append: yes
    become: yes
    tags:
      - install-docker

  ## oh-my-zsh
  #########################################
  - name: Install Oh My Zsh
    shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    args:
      executable: /bin/bash
      creates: /home/vagrant/.oh-my-zsh/
    become_user: "vagrant"
    changed_when: false
    tags:
      - install-ohmyzsh

  - name: Install zsh-autosuggestions plugin
    git:
      repo: https://github.com/zsh-users/zsh-autosuggestions
      dest: "/home/vagrant/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
      force: yes
    become_user: "vagrant"
    tags:
      - install-ohmyzsh

  - name: Enable zsh-autosuggestions plugin
    lineinfile:
      path: "/home/vagrant/.zshrc"
      backrefs: yes
      regexp: '^plugins=\((.*)\)'
      line: 'plugins=(\1 zsh-autosuggestions)'
    become_user: "vagrant"
    when: lookup('file', "/home/vagrant/.zshrc") is not search('zsh-autosuggestions')
    tags:
      - install-ohmyzsh

  - name: Set zsh as default shell
    user:
      name: "vagrant"
      shell: /bin/zsh
    tags:
      - install-ohmyzsh

  ## Nord VPN
  #########################################
  - name: NordVPN - Installation
    ansible.builtin.shell: "wget -qO - https://downloads.nordcdn.com/apps/linux/install.sh | sh -"
    tags:
      - install-nordvpn

  ## Burp community
  #########################################
  - name: Burp - Download
    ansible.builtin.get_url:
      url: https://portswigger.net/burp/releases/download?product=community&type=linux
      # other URL: https://portswigger.net/burp/releases/download?product=community&version=2023.5.1&type=linux
      dest: /tmp/burpcommunity.sh
      mode: '0755'
    tags: install-burp

  - name: Burp - Installation
    # this is to deal with burpcommunity prompt installtion
    #   This will install Burp Suite Community Edition on your computer.
    #   OK [o, Enter], Cancel [c]
    #   Where should Burp Suite Community Edition be installed?
    #   [/home/vagrant/BurpSuiteCommunity]
    #   Create symlinks?
    #   Yes [y, Enter], No [n]
    #   Select the folder where you would like Burp Suite Community Edition to create symlinks, then click Next.
    #   [/usr/local/bin]
    #   Extracting files ...
    #   ...
    ansible.builtin.shell:
      cmd: |-
        /tmp/burpcommunity.sh << EOF
        o
        /opt/BurpSuiteCommunity
        y
        /usr/local/bin
        EOF
      creates: /opt/BurpSuiteCommunity
    tags: install-burp

  ## OleVBA
  #########################################
  - name: Olevba - Install requirements
    ansible.builtin.apt:
      name:
        - python3
        - python3-pip
      state: present
      update_cache: yes
    tags: install-oletools

  - name: Olevba - Installation
    ansible.builtin.shell: python3 -m pip install --upgrade pip oletools
    tags: install-oletools

  ## pdfid, pdf-parser (DidierStensSuite)
  #########################################
  - name: Pdftools - Install pdf-to-text
    ansible.builtin.apt:
      name:
        - poppler-utils
      state: present
      update_cache: yes
    tags: install-pdftools

  - name: Pdftools - Cloning pdf github tools
    ansible.builtin.git:
      repo: 'https://github.com/DidierStevens/DidierStevensSuite.git'
      dest: '/opt/DidierStevensSuite'
      force: yes
    tags: install-pdftools

  - name: Pdftools - Set python alternatives
    ansible.builtin.command:
      cmd: update-alternatives --install /usr/bin/python python /usr/bin/python3 1
      creates: /etc/alternatives/python
    tags: install-pdftools

  - name: Pdftools - Adding execution permission to the pdf tools
    ansible.builtin.file:
      path: "/opt/DidierStevensSuite/{{ item }}"
      mode: '0755'
    loop:
      - pdf-parser.py
      - pdfid.py
    tags: install-pdftools

  - name: Pdftools - Adding pdftools to shell profile
    ansible.builtin.lineinfile:
      path: '/home/vagrant/.zshrc'
      line: 'export PATH=$PATH:/opt/DidierStevensSuite'
      state: present
    become_user: vagrant
    tags: install-pdftools

  ## Tesseract
  #########################################
  - name: Tesseract - Installation
    ansible.builtin.apt:
      name:
        - tesseract-ocr
      state: present
      update_cache: yes
    tags: install-tesseract

  - name: Tesseract - install fra package
    ansible.builtin.get_url:
      url: https://github.com/tesseract-ocr/tessdata/raw/4.00/fra.traineddata
      dest: /usr/share/tesseract-ocr/4.00/tessdata/
    tags: install-tesseract

  - name: Tesseract - install eng package
    ansible.builtin.get_url:
      url: https://github.com/tesseract-ocr/tessdata/raw/4.00/eng.traineddata
      dest: /usr/share/tesseract-ocr/4.00/tessdata/
    tags: install-tesseract

  ## Ghidra
  #########################################
  - name: Ghidra - Install requirements
    ansible.builtin.apt:
      name:
        - openjdk-17-jdk
        - wget
        - unzip
      state: present
      update_cache: yes
    tags: install-ghidra

  - name: Ghidra - Set the PATH environment for JAVA
    ansible.builtin.lineinfile:
      path: '/home/vagrant/.zshrc'
      line: 'export PATH=$PATH:/usr/lib/jvm/java-17-openjdk-amd64/bin/'
      state: present
    tags: install-ghidra

  - name: Ghidra - Download
    ansible.builtin.get_url:
      url: https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.3_build/ghidra_10.3_PUBLIC_20230510.zip
      dest: /tmp/ghidra.zip
    tags: install-ghidra

  - name: Ghidra - Unzip
    ansible.builtin.unarchive:
      src: /tmp/ghidra.zip
      dest: /opt/
      creates: /opt/ghidra
    tags: install-ghidra

  - name: Ghidra - Rename Ghidra directory
    ansible.builtin.shell:
      cmd: mv /opt/ghidra_* /opt/ghidra
      creates: /opt/ghidra
    tags: install-ghidra

  - name: Ghidra - Set the PATH environment variable
    ansible.builtin.lineinfile:
      path: '/home/vagrant/.zshrc'
      line: 'export PATH=$PATH:/opt/ghidra'
      state: present
    tags: install-ghidra

  - name: Ghidra - Create a .desktop shortcut for My Program
    copy:
      dest: /usr/share/applications/ghidra.desktop
      owner: root
      group: root
      mode: '0755'
      content: |
        [Desktop Entry]
        Type=Application
        Name=Ghidra
        Comment=Reverse engineer application
        Icon=/opt/ghidra/docs/GhidraClass/Intermediate/Images/GhidraLogo64.png
        Exec=/opt/ghidra/ghidraRun
        Terminal=false
        Categories=Utility;Application;
    tags: install-ghidra

  ## Brave
  #########################################
  - name: Brave - Import repository key
    ansible.builtin.apt_key:
      url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
      state: present
    tags: install-brave

  - name: Brave - Add the Brave Browser repository
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"
      state: present
    tags: install-brave

  - name: Brave - Install Brave Browser
    ansible.builtin.apt:
      name: brave-browser
      state: present
      update_cache: yes
