# ProtonVPN comes on its own file because it needs a reboot.
- hosts: all
  gather_facts: yes
  become: yes
  tasks:

  ## ProtonVPN
  #########################################
  # This is to not get prompted for root when using the cli.
  - name: ProtonVPN - add user as sudoers
    ansible.builtin.user:
      name: vagrant
      groups: sudo
      append: yes
    tags:
      - install-protonvpn

  # ubuntu is the default pick when you use the cli.
  - name: ProtonVPN - Remove ubuntu user
    ansible.builtin.user:
      name: ubuntu
      state: absent
      remove: yes
    tags:
      - install-protonvpn

  # we have to remove netplan configs, otherwise this conflicts with network manager and
  # it will not work with protonvpn
  - name: ProtonVPN - Remove netplan configs (conflict with network manager)
    ansible.builtin.file:
      path: "/etc/netplan/{{ item }}"
      state: absent
    with_items:
      - '50-cloud-init.yaml'
      - '50-vagrant.yaml'
    tags:
      - install-protonvpn

  - name: ProtonVPN - Apply netplan
    ansible.builtin.shell: netplan apply
    tags:
      - install-protonvpn

  - name: ProtonVPN - configure Network Manager
    ansible.builtin.copy:
      src: NetworkManager/protonvpn.conf
      dest: /etc/NetworkManager/conf.d/protonvpn.conf
      owner: root
      group: root
      mode: '0644'
    tags:
      - install-protonvpn

#  - name: ProtonVPN - restart NetworkManager
#    ansible.builtin.service:
#      name: NetworkManager
#      state: restarted
#      enabled: true
#    tags:
#      - install-protonvpn
#
  - name: ProtonVPN - reboot for proper network setup
    ansible.builtin.reboot:
      reboot_timeout: 300
    tags:
      - install-protonvpn

  - name: ProtonVPN - install depedencies
    ansible.builtin.apt:
      name:
        - python3-pip
      state: present
      update_cache: yes
    tags:
      - install-protonvpn

  - name: ProtonVPN - Download deb
    ansible.builtin.get_url:
      url: https://repo.protonvpn.com/debian/dists/stable/main/binary-all/protonvpn-stable-release_1.0.3_all.deb
      dest: /tmp/package.deb
      checksum: sha256:c409c819eed60985273e94e575fd5dfd8dd34baef3764fc7356b0f23e25a372c
    tags:
      - install-protonvpn

  - name: ProtonVPN - Install deb
    ansible.builtin.apt:
      deb: /tmp/package.deb
    tags:
      - install-protonvpn

  - name: ProtonVPN - Install package
    ansible.builtin.apt:
      name: protonvpn-cli
      update_cache: yes
    tags:
      - install-protonvpn

  - name: ProtonVPN - Upgrade required pip packages
    ansible.builtin.pip:
      name:
        - pyopenssl
        - cryptography
      state: latest
    tags:
      - install-protonvpn
