- hosts: all
  gather_facts: yes
  become: yes
  tasks:

  - name: VBox guest - Get Linux Kernel version
    command: uname -r
    register: kernel_version
    tags:
      - install-vbox-guest

  - name: VBox guest - Install required packages
    apt:
      name:
        - build-essential
        - dkms
        - linux-headers-{{ kernel_version.stdout }}
      state: present
      update_cache: yes
    tags:
      - install-vbox-guest

  - name: VBox guest - Ensure the mount point exists
    file:
      path: /mnt/cdrom
      state: directory
    tags:
      - install-vbox-guest

  - name: VBox guest - Mount the filesystem
    mount:
      path: /mnt/cdrom
      src: /dev/cdrom
      fstype: iso9660
      state: mounted
    tags:
      - install-vbox-guest

  - name: VBox guest - Run VBoxLinuxAdditions.run [stderr expected]
    command: sh /mnt/cdrom/VBoxLinuxAdditions.run
    ignore_errors: yes
    tags:
      - install-vbox-guest

  - name: VBox guest - Unmount the filesystem
    mount:
      path: /mnt/cdrom
      fstype: iso9660
      state: unmounted
    tags:
      - install-vbox-guest

  - name: VBox guest - Rebooting
    ansible.builtin.reboot:
      reboot_timeout: 300
