---
ansible_python_interpreter: /usr/bin/python3
###
# Virtualbox role
###
local_virtualbox_iso: /usr/share/virtualbox/VBoxGuestAdditions.iso
virtualbox_iso: /root/VBoxGuestAdditions.iso
virtualbox_x11: true
virtualbox_remove_os_packages: true
virtualbox_os_packages:
  - virtualbox-guest-additions-iso
  - virtualbox-guest-dkms
  - virtualbox-guest-source
  - virtualbox-guest-utils
  - virtualbox-guest-x11
virtualbox_version: auto