---
ansible_python_interpreter: /usr/bin/python3
###
# Virtualbox role
###
local_virtualbox_iso: /usr/share/virtualbox/VBoxGuestAdditions.iso
virtualbox_iso: /root/VBoxGuestAdditions.iso
virtualbox_x11: true
virtualbox_remove_os_packages: true
virtualbox_os_packages:
  - virtualbox-guest-additions-iso
  - virtualbox-guest-dkms
  - virtualbox-guest-source
  - virtualbox-guest-utils
  - virtualbox-guest-x11
virtualbox_version: auto

###
# Virtualbox role
###
# Edition can be one of: 'ce' (Community Edition) or 'ee' (Enterprise Edition).
docker_edition: 'ce'
docker_package: "docker-{{ docker_edition }}"
docker_package_state: present

# Service options.
docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted

# Docker Compose options.
docker_install_compose: true
docker_compose_version: "1.27.4"
docker_compose_path: /usr/local/bin/docker-compose

# Used only for Debian/Ubuntu. Switch 'stable' to 'edge' if needed.
docker_apt_release_channel: stable
docker_apt_arch: amd64
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
docker_apt_ignore_key_error: true
docker_apt_gpg_key: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg