targets:
  sandbox-01:
    box: ubuntu/jammy64
    version: 20230510.0.0
    # other ranges could fail?
    # see: https://github.com/hashicorp/vagrant/issues/12557
    ip: 192.168.56.105
    cpus: 3
    memory: 4096
    vram: 32
    installGuest: true  # only supported with Virtual Box
    gui: true
    reqAudio: false
    playbooks:
      - path: res/ansible/main.yml
        supplier: ansible_local
