targets:
  sandbox-01:
    virtualbox:
      box: ubuntu/jammy64
      version: 20230510.0.0
    parallels:
      box: bento/ubuntu-24.04
      version: 202407.22.0
    # other ranges could fail?
    # see: https://github.com/hashicorp/vagrant/issues/12557
    ip: 192.168.56.105 # doesn't work on parallels
    cpus: 3
    memory: 4096
    vram: 32
    installGuest: true  # only supported with Virtual Box
    gui: true
    reqAudio: false
    playbooks:
      - path: res/ansible/main.yml
        supplier: ansible_local
